/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsBuildingRouteImport } from './routes/docs/building'
import { Route as DocsGuidesTrainingRouteImport } from './routes/docs/guides/training'
import { Route as DocsGuidesPerformanceRouteImport } from './routes/docs/guides/performance'
import { Route as DocsGuidesEmbeddedRouteImport } from './routes/docs/guides/embedded'
import { Route as DocsArchitectureTensorsRouteImport } from './routes/docs/architecture/tensors'
import { Route as DocsArchitectureOverviewRouteImport } from './routes/docs/architecture/overview'
import { Route as DocsArchitectureGemmRouteImport } from './routes/docs/architecture/gemm'
import { Route as DocsArchitectureCudaRouteImport } from './routes/docs/architecture/cuda'
import { Route as DocsArchitectureComputeRouteImport } from './routes/docs/architecture/compute'
import { Route as DocsArchitectureAutogradRouteImport } from './routes/docs/architecture/autograd'
import { Route as DocsApiTensorRouteImport } from './routes/docs/api/tensor'
import { Route as DocsApiOptimizersRouteImport } from './routes/docs/api/optimizers'
import { Route as DocsApiModelRouteImport } from './routes/docs/api/model'
import { Route as DocsApiLossesRouteImport } from './routes/docs/api/losses'
import { Route as DocsApiLayersRouteImport } from './routes/docs/api/layers'
import { Route as DocsApiDataRouteImport } from './routes/docs/api/data'
import { Route as DocsApiAutogradRouteImport } from './routes/docs/api/autograd'
import { Route as DocsApiActivationsRouteImport } from './routes/docs/api/activations'

const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBuildingRoute = DocsBuildingRouteImport.update({
  id: '/docs/building',
  path: '/docs/building',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidesTrainingRoute = DocsGuidesTrainingRouteImport.update({
  id: '/docs/guides/training',
  path: '/docs/guides/training',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidesPerformanceRoute = DocsGuidesPerformanceRouteImport.update({
  id: '/docs/guides/performance',
  path: '/docs/guides/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidesEmbeddedRoute = DocsGuidesEmbeddedRouteImport.update({
  id: '/docs/guides/embedded',
  path: '/docs/guides/embedded',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureTensorsRoute = DocsArchitectureTensorsRouteImport.update({
  id: '/docs/architecture/tensors',
  path: '/docs/architecture/tensors',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureOverviewRoute =
  DocsArchitectureOverviewRouteImport.update({
    id: '/docs/architecture/overview',
    path: '/docs/architecture/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsArchitectureGemmRoute = DocsArchitectureGemmRouteImport.update({
  id: '/docs/architecture/gemm',
  path: '/docs/architecture/gemm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureCudaRoute = DocsArchitectureCudaRouteImport.update({
  id: '/docs/architecture/cuda',
  path: '/docs/architecture/cuda',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureComputeRoute = DocsArchitectureComputeRouteImport.update({
  id: '/docs/architecture/compute',
  path: '/docs/architecture/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsArchitectureAutogradRoute =
  DocsArchitectureAutogradRouteImport.update({
    id: '/docs/architecture/autograd',
    path: '/docs/architecture/autograd',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsApiTensorRoute = DocsApiTensorRouteImport.update({
  id: '/docs/api/tensor',
  path: '/docs/api/tensor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiOptimizersRoute = DocsApiOptimizersRouteImport.update({
  id: '/docs/api/optimizers',
  path: '/docs/api/optimizers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiModelRoute = DocsApiModelRouteImport.update({
  id: '/docs/api/model',
  path: '/docs/api/model',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiLossesRoute = DocsApiLossesRouteImport.update({
  id: '/docs/api/losses',
  path: '/docs/api/losses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiLayersRoute = DocsApiLayersRouteImport.update({
  id: '/docs/api/layers',
  path: '/docs/api/layers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiDataRoute = DocsApiDataRouteImport.update({
  id: '/docs/api/data',
  path: '/docs/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiAutogradRoute = DocsApiAutogradRouteImport.update({
  id: '/docs/api/autograd',
  path: '/docs/api/autograd',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiActivationsRoute = DocsApiActivationsRouteImport.update({
  id: '/docs/api/activations',
  path: '/docs/api/activations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/docs/building': typeof DocsBuildingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/api/activations': typeof DocsApiActivationsRoute
  '/docs/api/autograd': typeof DocsApiAutogradRoute
  '/docs/api/data': typeof DocsApiDataRoute
  '/docs/api/layers': typeof DocsApiLayersRoute
  '/docs/api/losses': typeof DocsApiLossesRoute
  '/docs/api/model': typeof DocsApiModelRoute
  '/docs/api/optimizers': typeof DocsApiOptimizersRoute
  '/docs/api/tensor': typeof DocsApiTensorRoute
  '/docs/architecture/autograd': typeof DocsArchitectureAutogradRoute
  '/docs/architecture/compute': typeof DocsArchitectureComputeRoute
  '/docs/architecture/cuda': typeof DocsArchitectureCudaRoute
  '/docs/architecture/gemm': typeof DocsArchitectureGemmRoute
  '/docs/architecture/overview': typeof DocsArchitectureOverviewRoute
  '/docs/architecture/tensors': typeof DocsArchitectureTensorsRoute
  '/docs/guides/embedded': typeof DocsGuidesEmbeddedRoute
  '/docs/guides/performance': typeof DocsGuidesPerformanceRoute
  '/docs/guides/training': typeof DocsGuidesTrainingRoute
}
export interface FileRoutesByTo {
  '/docs/building': typeof DocsBuildingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/api/activations': typeof DocsApiActivationsRoute
  '/docs/api/autograd': typeof DocsApiAutogradRoute
  '/docs/api/data': typeof DocsApiDataRoute
  '/docs/api/layers': typeof DocsApiLayersRoute
  '/docs/api/losses': typeof DocsApiLossesRoute
  '/docs/api/model': typeof DocsApiModelRoute
  '/docs/api/optimizers': typeof DocsApiOptimizersRoute
  '/docs/api/tensor': typeof DocsApiTensorRoute
  '/docs/architecture/autograd': typeof DocsArchitectureAutogradRoute
  '/docs/architecture/compute': typeof DocsArchitectureComputeRoute
  '/docs/architecture/cuda': typeof DocsArchitectureCudaRoute
  '/docs/architecture/gemm': typeof DocsArchitectureGemmRoute
  '/docs/architecture/overview': typeof DocsArchitectureOverviewRoute
  '/docs/architecture/tensors': typeof DocsArchitectureTensorsRoute
  '/docs/guides/embedded': typeof DocsGuidesEmbeddedRoute
  '/docs/guides/performance': typeof DocsGuidesPerformanceRoute
  '/docs/guides/training': typeof DocsGuidesTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/docs/building': typeof DocsBuildingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/api/activations': typeof DocsApiActivationsRoute
  '/docs/api/autograd': typeof DocsApiAutogradRoute
  '/docs/api/data': typeof DocsApiDataRoute
  '/docs/api/layers': typeof DocsApiLayersRoute
  '/docs/api/losses': typeof DocsApiLossesRoute
  '/docs/api/model': typeof DocsApiModelRoute
  '/docs/api/optimizers': typeof DocsApiOptimizersRoute
  '/docs/api/tensor': typeof DocsApiTensorRoute
  '/docs/architecture/autograd': typeof DocsArchitectureAutogradRoute
  '/docs/architecture/compute': typeof DocsArchitectureComputeRoute
  '/docs/architecture/cuda': typeof DocsArchitectureCudaRoute
  '/docs/architecture/gemm': typeof DocsArchitectureGemmRoute
  '/docs/architecture/overview': typeof DocsArchitectureOverviewRoute
  '/docs/architecture/tensors': typeof DocsArchitectureTensorsRoute
  '/docs/guides/embedded': typeof DocsGuidesEmbeddedRoute
  '/docs/guides/performance': typeof DocsGuidesPerformanceRoute
  '/docs/guides/training': typeof DocsGuidesTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docs/building'
    | '/docs/quickstart'
    | '/docs/api/activations'
    | '/docs/api/autograd'
    | '/docs/api/data'
    | '/docs/api/layers'
    | '/docs/api/losses'
    | '/docs/api/model'
    | '/docs/api/optimizers'
    | '/docs/api/tensor'
    | '/docs/architecture/autograd'
    | '/docs/architecture/compute'
    | '/docs/architecture/cuda'
    | '/docs/architecture/gemm'
    | '/docs/architecture/overview'
    | '/docs/architecture/tensors'
    | '/docs/guides/embedded'
    | '/docs/guides/performance'
    | '/docs/guides/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs/building'
    | '/docs/quickstart'
    | '/docs/api/activations'
    | '/docs/api/autograd'
    | '/docs/api/data'
    | '/docs/api/layers'
    | '/docs/api/losses'
    | '/docs/api/model'
    | '/docs/api/optimizers'
    | '/docs/api/tensor'
    | '/docs/architecture/autograd'
    | '/docs/architecture/compute'
    | '/docs/architecture/cuda'
    | '/docs/architecture/gemm'
    | '/docs/architecture/overview'
    | '/docs/architecture/tensors'
    | '/docs/guides/embedded'
    | '/docs/guides/performance'
    | '/docs/guides/training'
  id:
    | '__root__'
    | '/docs/building'
    | '/docs/quickstart'
    | '/docs/api/activations'
    | '/docs/api/autograd'
    | '/docs/api/data'
    | '/docs/api/layers'
    | '/docs/api/losses'
    | '/docs/api/model'
    | '/docs/api/optimizers'
    | '/docs/api/tensor'
    | '/docs/architecture/autograd'
    | '/docs/architecture/compute'
    | '/docs/architecture/cuda'
    | '/docs/architecture/gemm'
    | '/docs/architecture/overview'
    | '/docs/architecture/tensors'
    | '/docs/guides/embedded'
    | '/docs/guides/performance'
    | '/docs/guides/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsBuildingRoute: typeof DocsBuildingRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsApiActivationsRoute: typeof DocsApiActivationsRoute
  DocsApiAutogradRoute: typeof DocsApiAutogradRoute
  DocsApiDataRoute: typeof DocsApiDataRoute
  DocsApiLayersRoute: typeof DocsApiLayersRoute
  DocsApiLossesRoute: typeof DocsApiLossesRoute
  DocsApiModelRoute: typeof DocsApiModelRoute
  DocsApiOptimizersRoute: typeof DocsApiOptimizersRoute
  DocsApiTensorRoute: typeof DocsApiTensorRoute
  DocsArchitectureAutogradRoute: typeof DocsArchitectureAutogradRoute
  DocsArchitectureComputeRoute: typeof DocsArchitectureComputeRoute
  DocsArchitectureCudaRoute: typeof DocsArchitectureCudaRoute
  DocsArchitectureGemmRoute: typeof DocsArchitectureGemmRoute
  DocsArchitectureOverviewRoute: typeof DocsArchitectureOverviewRoute
  DocsArchitectureTensorsRoute: typeof DocsArchitectureTensorsRoute
  DocsGuidesEmbeddedRoute: typeof DocsGuidesEmbeddedRoute
  DocsGuidesPerformanceRoute: typeof DocsGuidesPerformanceRoute
  DocsGuidesTrainingRoute: typeof DocsGuidesTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/building': {
      id: '/docs/building'
      path: '/docs/building'
      fullPath: '/docs/building'
      preLoaderRoute: typeof DocsBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guides/training': {
      id: '/docs/guides/training'
      path: '/docs/guides/training'
      fullPath: '/docs/guides/training'
      preLoaderRoute: typeof DocsGuidesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guides/performance': {
      id: '/docs/guides/performance'
      path: '/docs/guides/performance'
      fullPath: '/docs/guides/performance'
      preLoaderRoute: typeof DocsGuidesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guides/embedded': {
      id: '/docs/guides/embedded'
      path: '/docs/guides/embedded'
      fullPath: '/docs/guides/embedded'
      preLoaderRoute: typeof DocsGuidesEmbeddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/tensors': {
      id: '/docs/architecture/tensors'
      path: '/docs/architecture/tensors'
      fullPath: '/docs/architecture/tensors'
      preLoaderRoute: typeof DocsArchitectureTensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/overview': {
      id: '/docs/architecture/overview'
      path: '/docs/architecture/overview'
      fullPath: '/docs/architecture/overview'
      preLoaderRoute: typeof DocsArchitectureOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/gemm': {
      id: '/docs/architecture/gemm'
      path: '/docs/architecture/gemm'
      fullPath: '/docs/architecture/gemm'
      preLoaderRoute: typeof DocsArchitectureGemmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/cuda': {
      id: '/docs/architecture/cuda'
      path: '/docs/architecture/cuda'
      fullPath: '/docs/architecture/cuda'
      preLoaderRoute: typeof DocsArchitectureCudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/compute': {
      id: '/docs/architecture/compute'
      path: '/docs/architecture/compute'
      fullPath: '/docs/architecture/compute'
      preLoaderRoute: typeof DocsArchitectureComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/architecture/autograd': {
      id: '/docs/architecture/autograd'
      path: '/docs/architecture/autograd'
      fullPath: '/docs/architecture/autograd'
      preLoaderRoute: typeof DocsArchitectureAutogradRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/tensor': {
      id: '/docs/api/tensor'
      path: '/docs/api/tensor'
      fullPath: '/docs/api/tensor'
      preLoaderRoute: typeof DocsApiTensorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/optimizers': {
      id: '/docs/api/optimizers'
      path: '/docs/api/optimizers'
      fullPath: '/docs/api/optimizers'
      preLoaderRoute: typeof DocsApiOptimizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/model': {
      id: '/docs/api/model'
      path: '/docs/api/model'
      fullPath: '/docs/api/model'
      preLoaderRoute: typeof DocsApiModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/losses': {
      id: '/docs/api/losses'
      path: '/docs/api/losses'
      fullPath: '/docs/api/losses'
      preLoaderRoute: typeof DocsApiLossesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/layers': {
      id: '/docs/api/layers'
      path: '/docs/api/layers'
      fullPath: '/docs/api/layers'
      preLoaderRoute: typeof DocsApiLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/data': {
      id: '/docs/api/data'
      path: '/docs/api/data'
      fullPath: '/docs/api/data'
      preLoaderRoute: typeof DocsApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/autograd': {
      id: '/docs/api/autograd'
      path: '/docs/api/autograd'
      fullPath: '/docs/api/autograd'
      preLoaderRoute: typeof DocsApiAutogradRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/activations': {
      id: '/docs/api/activations'
      path: '/docs/api/activations'
      fullPath: '/docs/api/activations'
      preLoaderRoute: typeof DocsApiActivationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DocsBuildingRoute: DocsBuildingRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsApiActivationsRoute: DocsApiActivationsRoute,
  DocsApiAutogradRoute: DocsApiAutogradRoute,
  DocsApiDataRoute: DocsApiDataRoute,
  DocsApiLayersRoute: DocsApiLayersRoute,
  DocsApiLossesRoute: DocsApiLossesRoute,
  DocsApiModelRoute: DocsApiModelRoute,
  DocsApiOptimizersRoute: DocsApiOptimizersRoute,
  DocsApiTensorRoute: DocsApiTensorRoute,
  DocsArchitectureAutogradRoute: DocsArchitectureAutogradRoute,
  DocsArchitectureComputeRoute: DocsArchitectureComputeRoute,
  DocsArchitectureCudaRoute: DocsArchitectureCudaRoute,
  DocsArchitectureGemmRoute: DocsArchitectureGemmRoute,
  DocsArchitectureOverviewRoute: DocsArchitectureOverviewRoute,
  DocsArchitectureTensorsRoute: DocsArchitectureTensorsRoute,
  DocsGuidesEmbeddedRoute: DocsGuidesEmbeddedRoute,
  DocsGuidesPerformanceRoute: DocsGuidesPerformanceRoute,
  DocsGuidesTrainingRoute: DocsGuidesTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
